spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/local}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:2}
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:1}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    aws:
      # No endpoint defined here; SDK will auto-resolve in AWS
      region:
        static: ${AWS_REGION:ap-southeast-2}

server:
  port: 8084
  address: 0.0.0.0

notification:
  queue:
    name: ${NOTIFICATION_QUEUE:notification-queue}

# This should be injected via Task Definition for security
SECRET_KEY: ${SECRET_KEY}