name: Build and Push Docker Images

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          [
            molymarket-notification-service,
            molymarket-payment-service,
            molymarket-product-order-service,
            molymarket-uam-service,
          ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: echo "LOWER_OWNER=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
        shell: bash

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: backend/${{ matrix.service }}
          push: ${{ github.event_name == 'push' }}
          tags: |
            ghcr.io/${{ env.LOWER_OWNER }}/${{ matrix.service }}:latest
            ghcr.io/${{ env.LOWER_OWNER }}/${{ matrix.service }}:${{ github.sha }}
